### PR TITLE
Handling create_at so it complais with MongoDate standard

### PR DESCRIPTION
**Pull request by ldynia**
This applys for a projects developed on top of Mongodb. In mongodb create_at is stored as a MongoDat that, looks like this:
~~~json
{
"created_at": {
     "date": "2015-03-31 13:33:07",
     "timezone_type": NumberInt(3),
     "timezone": "UTC"
   } 
}
~~~
Therefor, original check in reminderExpired() of DatabaseTokenRepository throws exception. This pull request fixes the error.

Greetigns

### CODE REVIEW

**Comment by sboo** [comment]
I updated the code to reflect the Laravel 5 version which I'd assume should be compatible with MondgoDB. Can you check?

**Comment by ldynia** [comment]
Hi @sboo unfortunatelly, this changes are not compatible with mongodb. I added another commit that fixes the error. Cheers!

**Comment by sboo** [comment]
You still had a bug in your code, but I resolved it. Gonna close the pull request, but it's fixed for mongodb support

**Comment by ldynia** [comment]
awesome thanks!

**Pull request closed without merging**
